---
- name: Configure local development environment
  hosts: all

  vars_files:
    - vars/default.config.yml
  
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      tags: [ 'always' ]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: [ 'homebrew' ]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: [ 'dock' ]

  tasks:
    - name: Register Git user and email
      shell: |
        git config --global user.name "{{ git.global.user_name }}"
        git config --global user.email "{{ git.global.user_email }}"

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: [ 'post' ]
